# Generated by Django 4.2.7 on 2023-11-08 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Пустой заголовок', max_length=72, verbose_name='Заголовок')),
                ('content', models.TextField(default='', help_text='текст подсказки', max_length=4048, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='advertisements/videos/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tank', 'Танк'), ('Hiller', 'Хиллер'), ('DD', 'Дамаг диллер'), ('Merchants', 'Торговец'), ('Guildmasters', 'Гилдмастер'), ('Questgivers', 'Квестгивер'), ('Blacksmiths', 'Кузнец'), ('Tanners', 'Кожевник'), ('Potions_brewers', 'Зельевар'), ('Spell_masters', 'Мастер заклинаний')], default='Tank', max_length=72, verbose_name='Категория объявления')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='имя')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', help_text='текст отлкика', max_length=4048)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('active', models.BooleanField(default=False)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response_announcement', to='Notice_board.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Response_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announcement_category', to='Notice_board.category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announcement_user', to='Notice_board.userprofile', verbose_name='Автор'),
        ),
    ]
