# Generated by Django 4.2.7 on 2023-11-08 05:35

import Notice_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Notice_board.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
