# Generated by Django 4.2.7 on 2023-11-08 05:46

import Notice_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notice_board', '0002_alter_announcement_image_alter_announcement_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Notice_board.models.user_video_path),
        ),
    ]
