# Generated by Django 4.2.7 on 2023-12-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notice_board', '0003_alter_announcement_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='active',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='announcement',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
